Return-Path: <linux-raid-owner@vger.kernel.org>
X-Original-To: lists+linux-raid@lfdr.de
Delivered-To: lists+linux-raid@lfdr.de
Received: from out1.vger.email (out1.vger.email [IPv6:2620:137:e000::1:20])
	by mail.lfdr.de (Postfix) with ESMTP id 497C677709A
	for <lists+linux-raid@lfdr.de>; Thu, 10 Aug 2023 08:42:31 +0200 (CEST)
Received: (majordomo@vger.kernel.org) by vger.kernel.org via listexpand
        id S230120AbjHJGm1 (ORCPT <rfc822;lists+linux-raid@lfdr.de>);
        Thu, 10 Aug 2023 02:42:27 -0400
Received: from lindbergh.monkeyblade.net ([23.128.96.19]:60414 "EHLO
        lindbergh.monkeyblade.net" rhost-flags-OK-OK-OK-OK) by vger.kernel.org
        with ESMTP id S229789AbjHJGm1 (ORCPT
        <rfc822;linux-raid@vger.kernel.org>); Thu, 10 Aug 2023 02:42:27 -0400
Received: from mx3.molgen.mpg.de (mx3.molgen.mpg.de [141.14.17.11])
        by lindbergh.monkeyblade.net (Postfix) with ESMTPS id 8CE5FE4B
        for <linux-raid@vger.kernel.org>; Wed,  9 Aug 2023 23:42:25 -0700 (PDT)
Received: from [192.168.0.2] (unknown [95.91.208.105])
        (using TLSv1.3 with cipher TLS_AES_128_GCM_SHA256 (128/128 bits)
         key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256)
        (No client certificate requested)
        (Authenticated sender: pmenzel)
        by mx.molgen.mpg.de (Postfix) with ESMTPSA id 526DB61E5FE07;
        Thu, 10 Aug 2023 08:42:02 +0200 (CEST)
Message-ID: <2c18c875-bc00-465a-9e19-c66d63c07987@molgen.mpg.de>
Date:   Thu, 10 Aug 2023 08:42:01 +0200
MIME-Version: 1.0
User-Agent: Mozilla Thunderbird
Subject: Re: [PATCH] md: raid0: account for split bio in iostat accounting
Content-Language: en-US
To:     David Jeffery <djeffery@redhat.com>
Cc:     Song Liu <song@kernel.org>, linux-raid@vger.kernel.org,
        Laurence Oberman <loberman@redhat.com>
References: <20230809171722.11089-1-djeffery@redhat.com>
From:   Paul Menzel <pmenzel@molgen.mpg.de>
In-Reply-To: <20230809171722.11089-1-djeffery@redhat.com>
Content-Type: text/plain; charset=UTF-8; format=flowed
Content-Transfer-Encoding: 7bit
X-Spam-Status: No, score=-1.9 required=5.0 tests=BAYES_00,
        RCVD_IN_DNSWL_BLOCKED,SPF_HELO_NONE,SPF_PASS autolearn=ham
        autolearn_force=no version=3.4.6
X-Spam-Checker-Version: SpamAssassin 3.4.6 (2021-04-09) on
        lindbergh.monkeyblade.net
Precedence: bulk
List-ID: <linux-raid.vger.kernel.org>
X-Mailing-List: linux-raid@vger.kernel.org

Dear David,


Thank you for your patch.

Am 09.08.23 um 19:16 schrieb David Jeffery:
> When a bio is split by md raid0, the newly created bio will not be tracked
> by md for I/O accounting. Only the portion of I/O still assigned to the
> original bio which was reduced by the split will be accounted for. This
> results in md iostat data sometimes showing I/O values far below the actual
> amount of data being sent through md.
> 
> md_account_bio() needs to be called for all bio generated by the bio split.

Could you please add how you tested this?

> Signed-off-by: David Jeffery <djeffery@redhat.com>
> Tested-by: Laurence Oberman <loberman@redhat.com>
> ---
>   drivers/md/raid0.c | 3 +--
>   1 file changed, 1 insertion(+), 2 deletions(-)
> 
> diff --git a/drivers/md/raid0.c b/drivers/md/raid0.c
> index d1ac73fcd852..1fd559ac8c68 100644
> --- a/drivers/md/raid0.c
> +++ b/drivers/md/raid0.c
> @@ -597,8 +597,7 @@ static bool raid0_make_request(struct mddev *mddev, struct bio *bio)
>   		bio = split;
>   	}
>   
> -	if (bio->bi_pool != &mddev->bio_set)
> -		md_account_bio(mddev, &bio);
> +	md_account_bio(mddev, &bio);
>   
>   	orig_sector = sector;
>   	zone = find_zone(mddev->private, &sector);


Kind regards,

Paul
